  
language: php

php:
  - 7.2
  
before_install:
  - echo "BEFORE INSTALL START"
  - gem install bundler
  - echo "BEFORE INSTALL END"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-source --no-interaction --dev
  - cp .env.example .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit